server:
  port: ${SERVER_PORT:8081}
spring:
  data:
    mongodb:
      uri: your-mongodb-host
      database: kikwiflow_db
      auto-index-creation: true
kikwiflow:
  rest:
   # base-path: "engine/teste"
    cors:
      allowed-origins: "http://localhost:3000"
  stats:
    enabled: false
  outbox:
    events-enabled: false
  pulse:
    sse-endpoints:
      enabled: true #Default true
      interval: 5000 # default 5000




