graph TD
    subgraph "kikwi-pulse Cockpit"
        UI[UI Angular]
    end

    subgraph "Serviço de Gestão BFF"
        BFF[API REST]
        MgmtCore[kikwi-management-core]
    end

    subgraph "Aplicação de Negócio"
        Engine[kikwi-core]
    end

subgraph "Camada de Persistência Contrato"
PersistenceAPI[kikwi-runtime-persistence-api<br>ProcessExecutionRepository]
end

subgraph "Implementação da Persistência Ex: MongoDB"
PersistenceImpl[kikwi-persistence-mongodb]
end

subgraph "Base de Dados"
DB_Primary[Base de Dados Primária]
DB_Replica[Base de Dados Réplica]
end

UI -- HTTP --> BFF
BFF --> MgmtCore

MgmtCore -- Comando --> Engine
MgmtCore -- Query --> PersistenceAPI

Engine -- Comando --> PersistenceAPI

BFF -- inclui dependência --> PersistenceImpl
PersistenceImpl -- implementa --> PersistenceAPI

PersistenceImpl -- Escrita --> DB_Primary
PersistenceImpl -- Leitura --> DB_Replica

DB_Primary -- Replicação --> DB_Replica